-- ============================================================================
-- RMS Sync v3.0 - Schéma SQL Complet et Définitif
-- Toutes les colonnes identifiées, noms standardisés
-- ============================================================================

-- ============================================================================
-- 1. TABLES DE CONFIGURATION
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.hotels (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    hotel_id TEXT NOT NULL UNIQUE,
    hotel_name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.import_templates (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    source_type TEXT CHECK (source_type IN ('csv', 'excel')),
    target_table TEXT NOT NULL,
    sheet_name TEXT,
    column_mapping JSONB NOT NULL DEFAULT '{}',
    column_types JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS et Policies
ALTER TABLE public.hotels ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.import_templates ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all for service role" ON public.hotels;
CREATE POLICY "Allow all for service role" ON public.hotels FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for service role" ON public.import_templates;
CREATE POLICY "Allow all for service role" ON public.import_templates FOR ALL USING (true) WITH CHECK (true);

-- ============================================================================
-- 2. D-EDGE PLANNING
-- ============================================================================

CREATE TABLE IF NOT EXISTS public."D-EDGE PLANNING TARIFS DISPO ET PLANS TARIFAIRES" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    hotel_id TEXT,
    "TYPE DE CHAMBRE" TEXT,
    "PLAN TARIFAIRE" TEXT,
    "LEFT FOR SALE" TEXT,
    date DATE,
    "TARIF / DISPO" TEXT
);

-- ============================================================================
-- 3. D-EDGE RÉSERVATIONS (Structure complète)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public."D-EDGE RÉSERVATIONS EN COURS" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    hotel_id TEXT,
    "Id GDS" TEXT,
    "Statut" TEXT,
    "Date de réserv." DATE,
    "Date Arrivée" DATE,
    "Date Départ" DATE,
    "Nb nuit(s)" TEXT,
    "Client" TEXT,
    "Société" TEXT,
    "Chambre" TEXT,
    "Typologie" TEXT,
    "Plan tarifaire" TEXT,
    "Gains" TEXT,
    "Commission" TEXT,
    "Source" TEXT,
    "Canal" TEXT,
    "Nombre de pers." TEXT,
    "Adultes" TEXT,
    "Enfants" TEXT,
    "Bébés" TEXT,
    "Commentaires" TEXT,
    "Assurance annulation" TEXT,
    "Montant assurance" TEXT,
    "Code promo" TEXT,
    "Petit déjeuner" TEXT,
    "Parking" TEXT,
    "Animaux" TEXT,
    "Extras" TEXT
);

CREATE TABLE IF NOT EXISTS public."D-EDGE HISTORIQUE DES RÉSERVATIONS N-1" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    hotel_id TEXT,
    "Id GDS" TEXT,
    "Statut" TEXT,
    "Date de réserv." DATE,
    "Date Arrivée" DATE,
    "Date Départ" DATE,
    "Nb nuit(s)" TEXT,
    "Client" TEXT,
    "Société" TEXT,
    "Chambre" TEXT,
    "Typologie" TEXT,
    "Plan tarifaire" TEXT,
    "Gains" TEXT,
    "Commission" TEXT,
    "Source" TEXT,
    "Canal" TEXT,
    "Nombre de pers." TEXT,
    "Adultes" TEXT,
    "Enfants" TEXT,
    "Bébés" TEXT,
    "Commentaires" TEXT,
    "Assurance annulation" TEXT,
    "Montant assurance" TEXT,
    "Code promo" TEXT,
    "Petit déjeuner" TEXT,
    "Parking" TEXT,
    "Animaux" TEXT,
    "Extras" TEXT
);

-- ============================================================================
-- 4. OTA INSIGHT - Structure standardisée
-- ============================================================================

-- OTA APERÇU
CREATE TABLE IF NOT EXISTS public."OTA APERÇU" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    hotel_id TEXT,
    jour TEXT,
    date DATE,
    votre_hotel_le_plus_bas TEXT,
    tarif_le_plus_bas_mediane_du_compset TEXT,
    classement_des_tarifs_du_compset TEXT,
    demande_du_march TEXT,
    bookingcom_classement TEXT,
    jours_feries TEXT,
    evenements TEXT
);

-- OTA TARIFS CONCURRENCE
CREATE TABLE IF NOT EXISTS public."OTA TARIFS CONCURRENCE" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    hotel_id TEXT,
    jour TEXT,
    date DATE,
    demande_du_march TEXT,
    folkestone_opra TEXT,
    hotel_madeleine_haussmann TEXT,
    hotel_de_larcade TEXT,
    hotel_cordelia_opra_madeleine TEXT,
    queen_mary_opera TEXT,
    hotel_du_triangle_dor TEXT,
    best_western_plus_hotel_sydney_opera TEXT,
    hotel_opra_opal TEXT,
    hotel_royal_opra TEXT,
    hotel_george_sand_opra_paris TEXT,
    hotel_chavanel TEXT
);

-- OTA VS HIER
CREATE TABLE IF NOT EXISTS public."OTA VS HIER" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    hotel_id TEXT,
    jour TEXT,
    date DATE,
    demande_du_march TEXT,
    folkestone_opra TEXT,
    hotel_madeleine_haussmann TEXT,
    hotel_de_larcade TEXT,
    hotel_cordelia_opra_madeleine TEXT,
    queen_mary_opera TEXT,
    hotel_du_triangle_dor TEXT,
    best_western_plus_hotel_sydney_opera TEXT,
    hotel_opra_opal TEXT,
    hotel_royal_opra TEXT,
    hotel_george_sand_opra_paris TEXT,
    hotel_chavanel TEXT
);

-- OTA VS 3 JOURS
CREATE TABLE IF NOT EXISTS public."OTA VS 3 JOURS" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    hotel_id TEXT,
    jour TEXT,
    date DATE,
    demande_du_march TEXT,
    folkestone_opra TEXT,
    hotel_madeleine_haussmann TEXT,
    hotel_de_larcade TEXT,
    hotel_cordelia_opra_madeleine TEXT,
    queen_mary_opera TEXT,
    hotel_du_triangle_dor TEXT,
    best_western_plus_hotel_sydney_opera TEXT,
    hotel_opra_opal TEXT,
    hotel_royal_opra TEXT,
    hotel_george_sand_opra_paris TEXT,
    hotel_chavanel TEXT
);

-- OTA VS 7 JOURS
CREATE TABLE IF NOT EXISTS public."OTA VS 7 JOURS" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    hotel_id TEXT,
    jour TEXT,
    date DATE,
    demande_du_march TEXT,
    folkestone_opra TEXT,
    hotel_madeleine_haussmann TEXT,
    hotel_de_larcade TEXT,
    hotel_cordelia_opra_madeleine TEXT,
    queen_mary_opera TEXT,
    hotel_du_triangle_dor TEXT,
    best_western_plus_hotel_sydney_opera TEXT,
    hotel_opra_opal TEXT,
    hotel_royal_opra TEXT,
    hotel_george_sand_opra_paris TEXT,
    hotel_chavanel TEXT
);

-- ============================================================================
-- 5. SALONS & ÉVÉNEMENTS
-- ============================================================================

CREATE TABLE IF NOT EXISTS public."DATES SALONS ET ÉVÉNEMENTS" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    hotel_id TEXT,
    "Date début" DATE,
    "Date fin" DATE,
    "Nom de l'événement" TEXT,
    "Type" TEXT,
    "Lieu" TEXT,
    "Description" TEXT
);

-- ============================================================================
-- 6. FONCTIONS HELPER
-- ============================================================================

-- Fonction pour exécuter du SQL dynamique
CREATE OR REPLACE FUNCTION public.execute_sql(sql text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    EXECUTE sql;
END;
$$;

-- Fonction pour lister les tables
CREATE OR REPLACE FUNCTION public.get_public_tables()
RETURNS TABLE (table_name TEXT, table_type TEXT)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT t.table_name::TEXT, t.table_type::TEXT
    FROM information_schema.tables t
    WHERE t.table_schema = 'public'
    AND t.table_name NOT LIKE 'pg_%'
    AND t.table_name NOT LIKE 'sql_%'
    AND t.table_name != 'import_templates'
    ORDER BY t.table_name;
END;
$$;

-- Fonction pour lister les colonnes d'une table
CREATE OR REPLACE FUNCTION public.get_table_columns(t_name TEXT)
RETURNS TABLE (column_name TEXT, data_type TEXT, is_nullable TEXT)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT c.column_name::TEXT, c.data_type::TEXT, c.is_nullable::TEXT
    FROM information_schema.columns c
    WHERE c.table_schema = 'public'
    AND c.table_name = t_name
    AND c.column_name NOT IN ('id', 'created_at')
    ORDER BY c.ordinal_position;
END;
$$;

-- Vue résumé des templates
CREATE OR REPLACE VIEW public.v_template_summary AS
SELECT id, name, target_table, source_type, updated_at
FROM public.import_templates
ORDER BY updated_at DESC;

-- ============================================================================
-- 7. POLITIQUES RLS POUR TOUTES LES TABLES
-- ============================================================================

DO $$
DECLARE
    t text;
    tables text[] := ARRAY[
        'D-EDGE PLANNING TARIFS DISPO ET PLANS TARIFAIRES',
        'D-EDGE RÉSERVATIONS EN COURS',
        'D-EDGE HISTORIQUE DES RÉSERVATIONS N-1',
        'OTA APERÇU',
        'OTA TARIFS CONCURRENCE',
        'OTA VS HIER',
        'OTA VS 3 JOURS',
        'OTA VS 7 JOURS',
        'DATES SALONS ET ÉVÉNEMENTS'
    ];
BEGIN
    FOREACH t IN ARRAY tables LOOP
        BEGIN
            EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
            EXECUTE format('DROP POLICY IF EXISTS "Allow all" ON public.%I', t);
            EXECUTE format('CREATE POLICY "Allow all" ON public.%I FOR ALL USING (true) WITH CHECK (true)', t);
        EXCEPTION WHEN OTHERS THEN
            RAISE NOTICE 'Erreur RLS pour %: %', t, SQLERRM;
        END;
    END LOOP;
END $$;

-- ============================================================================
-- 8. INDEX POUR PERFORMANCE
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_import_templates_target ON public.import_templates(target_table);
CREATE INDEX IF NOT EXISTS idx_hotels_hotel_id ON public.hotels(hotel_id);

-- Commentaires
COMMENT ON TABLE public.import_templates IS 'Configuration ETL pour RMS Sync v3.0';
COMMENT ON TABLE public.hotels IS 'Liste des hôtels gérés par le système';
